name: typetalk
description: "MBTI based social chat application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  
  # Firebase (최신 호환 버전)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.2.3
  
  # 소셜 로그인
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.3
  
  # 위치 기반 기능
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1
  
  # 공유 기능
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Pretendard
  #     fonts:
  #       - asset: assets/fonts/Pretendard-Regular.otf
  #       - asset: assets/fonts/Pretendard-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/Pretendard-Bold.otf
  #         weight: 700