name: typetalk
description: "MBTI based social chat application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  
  # Firebase (임시 비활성화)
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # cloud_firestore: ^4.13.6
  # firebase_analytics: ^10.7.4
  # firebase_crashlytics: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Pretendard
  #     fonts:
  #       - asset: assets/fonts/Pretendard-Regular.otf
  #       - asset: assets/fonts/Pretendard-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/Pretendard-Bold.otf
  #         weight: 700