// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2qhmldX5gf4ztwWPqnnZwykX_h65WWv4',
    appId: '1:805092955656:web:57e99fa547805cf9ef63bd',
    messagingSenderId: '805092955656',
    projectId: 'typetalk-3dc68',
    authDomain: 'typetalk-3dc68.firebaseapp.com',
    storageBucket: 'typetalk-3dc68.firebasestorage.app',
    measurementId: 'G-3M0D1RF8KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiUC82o5hHvysDbF3XAx9GQwkew6FqaIU',
    appId: '1:805092955656:android:6a86c830a06d5b3def63bd',
    messagingSenderId: '805092955656',
    projectId: 'typetalk-3dc68',
    storageBucket: 'typetalk-3dc68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Mis1DThMy1QCFu4A7UCzjHB7nm8HVZU',
    appId: '1:805092955656:ios:da27e9062f914b98ef63bd',
    messagingSenderId: '805092955656',
    projectId: 'typetalk-3dc68',
    storageBucket: 'typetalk-3dc68.firebasestorage.app',
    iosBundleId: 'net.levelupcode.typetalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Mis1DThMy1QCFu4A7UCzjHB7nm8HVZU',
    appId: '1:805092955656:ios:da27e9062f914b98ef63bd',
    messagingSenderId: '805092955656',
    projectId: 'typetalk-3dc68',
    storageBucket: 'typetalk-3dc68.firebasestorage.app',
    iosBundleId: 'net.levelupcode.typetalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2qhmldX5gf4ztwWPqnnZwykX_h65WWv4',
    appId: '1:805092955656:web:57e99fa547805cf9ef63bd',
    messagingSenderId: '805092955656',
    projectId: 'typetalk-3dc68',
    storageBucket: 'typetalk-3dc68.firebasestorage.app',
  );
}